### ISSUE TITLE
Kiker APM tool support for TIBCO BW java 

### ISSUE THREAD

**Issue by prashantnitt07** [kieker-monitoring/infrastructure#1]
hi ,
Kiker APM tool is supported for 
1 . Weblogic 
2. Tomcat
3. JBOSS
4. TIBCO BW

please  provide link or guide for installed Kiker APM tools on LInux Machine ,
architecture , Latest release Kiker APM software.

**Comment by prashantnitt07** [comment]
please reply as soon as possible

**Comment by duelle** [comment]
Hi @prashantnitt07,
in this repository we store the scripts for maintaining our own infrastructure for running Jenkins workers and live demo machines. Therefor, this is not the place for requests regarding the Kieker Monitoring Framework itself.
You can find the Kieker Monitoring Framework repository here: https://github.com/kieker-monitoring/kieker
For further details, please refer to the Kieker website (e.g., documentation, support): http://kieker-monitoring.net/
There you can find the Kieker User Guide, the issue tracker for Kieker and links to the Kieker mailing lists.
